### ISSUE TITLE
Garbled characters in some PDFs

### ISSUE THREAD

**Issue by chenghaibo24** [tuxxy/IACR-eprint-mirror#1]
For example, IACR-eprint-mirror/2002/059.pdf. 
Copying the title gets ÍÒiÚeÖ×aÐÐÝ CÓÑÔÓ×abÐe ÆÓØiÓÒ× Óf ÃeÝ EÜ haÒge aÒd Ëe ÙÖe ChaÒÒeÐ× £

**Comment by tuxxy** [comment]
Hi, @chenghaibo24.

Unfortunately, there's nothing I can do about these kinds of issues since I'm just mirroring the archive to GitHub.

It's better to email the authors directly with such problems in the hopes that they will fix them and upload it to the IACR eprint archive.
